#tomcat端口
server:
  port: 9050

#DB配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rrsn

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/**/*Mapper.xml
  #实体扫描
  type-aliases-package: com.hicola.model
  type-enums-package: com.hicola.**.enums
  global-config:
    #逻辑删除配置
    db-config:
      id-type: assign_uuid
      #删除前
      logic-not-delete-value: 1
      #删除后
      logic-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#日志配置
logging:
  config: classpath:logback.xml
